### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by jonasraoni**
Hey @donatj,

I just got your `v3wip` branch, rebased, added minor updates and it's passing through the tests.

### CODE REVIEW

**Comment by donatj** [comment]
Very cool!

I'll need to poke and prod this later, I'm AFK for a couple days, but I'm excited to this.

**Comment by jonasraoni** [comment]
No problem, I'm just helping another open source project that would like to run their tests under Windows 😁

**Comment by jonasraoni** [comment]
I've just checked and I can confirm these updates worked for my use case.

**Comment by donatj** [comment]
Sorry for the delay in getting this merged. I really wanted to get PHP running on a Windows system and give it a try before hand.

After hamfisting my way through getting PHP going on Windows (you guys really configure PATH with a GUI?!) everything appears to work as expected.

**Comment by donatj** [comment]
Also, I just want to be sassy and add "why you wouldn't just use WSL is a mystery to me" 😆

**Comment by donatj** [comment]
Hmmph. Once I merged it, I'm getting a semi-consistent CI failure on PHP 5.5... Well that's no fun

**Comment by jonasraoni** [comment]
> you guys really configure PATH with a GUI?!

@donatj Windows got some new things, there's a [Windows Server Core](https://docs.microsoft.com/en-us/windows-server/administration/server-core/what-is-server-core), which has no GUI, and the [PowerShell](https://docs.microsoft.com/en-us/powershell/). Before the introduction of PowerShell, I think you'd have to use the [setx](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx) :)

> why you wouldn't just use WSL is a mystery to me

I'm just helping another repo, but I think it makes sense to have a test against Windows, considering minor differences might break something (e.g. `PHP_EOL`) 🤔

> CI failure on PHP 5.5

Let me know if you need a hand 😅

**Comment by jonasraoni** [comment]
Also, if you're ok to release a "broken" package (considering that it wasn't working in Windows anyway, it's already an improvement), I'll use it in the other repository and clear one debt 😅

**Pull request merged**
