### PR TITLE
Fix documentation example for Response by Method

### PR DESCRIPTION
**Pull request by Aoshido**

### CODE REVIEW

**Comment by donatj** [comment]
Hey, thanks for the contribution.  The README is actually generated via the instructions in mddoc.xml via this little tool: https://github.com/donatj/mddoc

It looks like we've just got the wrong example file in the `<source …>` and `<exec …>` sections

https://github.com/donatj/mock-webserver/blob/69393ff511a6c01dcd637e8a6e53ed111731f3b8/mddoc.xml#L63-L68 

If you wanted to change those `example/multi.php` to `example/methods.php` and make sure example/methods.php is to your liking, that'd be appreciated.

Bonus points for installing and running mddoc, but it's super alpha software so I don't know if it'll work for you ;)

**Comment by Aoshido** [comment]
Oh nice, I did not knew that, I'll see if I can change the mddoc.xml. After changing the file, if I ran the mddoc, the result should be the same right (So I don't do several commits lol)? 
The methods.php seems fine, I'm already using it!

**Comment by donatj** [comment]
Yep, if the example you have matches the `example/methods.php` you shouldn't change the README

**Comment by donatj** [comment]
Thank you kindly! I would have just done it myself, but I wanted you to get the credit ;)

**Comment by Aoshido** [comment]
Thank you! I really wanted to contribute!

**Pull request merged**
