### PR TITLE
Alternate Method to Vary on Method

### LINKED ISSUE #3: Add support for variance by HTTP verb
Is it possible to add support for the HTTP verb ?

Something like: 

`        $server->setResponseOfPath(
            '/api/v1/users/5',
            '[user object]',
            [],
            200,
            'PUT'
        );`

### PR DESCRIPTION
**Pull request by donatj**
Resolves #3 
Replaces #8

Adds a `ResponseByMethod` response object that allows you to vary the response by given method.

### CODE REVIEW

**Comment by donatj** [comment]
@stevenrombauts I slept on it - and I have decided I'd rather handle varying by method with a new Response object.

The reasoning being in the future I'd like to be able to add *other* ways of varying responses as well. For example via GET parameters – which would resolve #6.

Adding a new optional method parameter every time I decide I want to vary on something isn't ideal. 

Let me know if you have any objections, otherwise I will likely be merging and tagging this tonight.

I've kept your commits to acknowledge your contribution for which I am still quite grateful, and did kick the entire thing off ;)

**Comment by donatj** [comment]
You can see from the updated example https://github.com/donatj/mock-webserver/blob/64c0b8e23d4544863b620eb266c07253f422b989/example/methods.php how it would be used.

**Comment by stevenrombauts** [comment]
@donatj Nice, I like this approach much better, makes for cleaner code and adding more types of Response objects this way will make it much easier to extend in the future. Thanks and I'm sorry I gave you so much work ;-)

**Comment by donatj** [comment]
@stevenrombauts Haha, no worries man - I'd been putting it off for WAY WAY too long.

**Pull request merged**
